name: windows
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: windows-2019
    defaults:
      run:
        shell: bash
    steps:
      - name: "Setup"
        run: |
          gcc --version
