name: windows
on:
  push:
    branches:
      - dev

jobs:
  test:
    name: MinGW GC
    runs-on: windows-2019
    steps:
      - name: Install Vulkan SDK
      # You may pin to the exact commit or the version.
      # uses: humbletim/install-vulkan-sdk@6aadcb709dbb8e4096dad20e35adaefec83d4b45
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          # official Vulkan SDK release version to use
          version: 1.3.275.0
        
      - name: Install MinGW
        uses: e-t-l/setup-mingw@patch-1
        
      - name: "Setup"
        shell:
          bash
        run: |
          pacman -Syu git make mingw-w64-x86_64-SDL2 mingw-w64-x86_64-cmake mingw-w64-x86_64-python-pip mingw-w64-x86_64-qt5 mingw-w64-x86_64-toolchain autoconf libtool automake-wrapper --noconfirm

