name: windows
on:
  push:
    branches:
      - dev

jobs:
  test:
    name: MinGW GC
    runs-on: windows-2019
    defaults:
      run:
        shell: bash
    steps:
      - name: "Setup"
        run: |
          gcc --version
